# Generated by Django 3.1.7 on 2021-03-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=20)),
                ('emailaddress', models.TextField(max_length=200)),
                ('primary_no', models.CharField(max_length=12)),
                ('comments', models.CharField(max_length=2000)),
            ],
        ),
    ]
